/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EquipmentOrdered.java
 *
 * Created on 2012-12-18, 20:04:02
 */
package loweruserclient;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.util.Date;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import commobject.LocationTypeArray;

import socketclient.SocketClient;
import superuserclient.NewMend;


/**
 *
 * @author DELL
 */
public class EquipmentOrdered extends javax.swing.JPanel {

	final static int MaxOrderedNum = 1;
	int orderedNum ;
	
	String userid;
	String location;
	Vector <String> v_eqpId;
	
	 String sql;
	 SocketClient c;
	 Vector<String> v_result;
	
	//自己添加的变量	 
    Vector <String> head ;
    Vector<Vector> data;
    DefaultTableModel dtm;
	
	/** Creates new form EquipmentOrdered */
    public EquipmentOrdered(String userid,String location) {
    	this.userid = userid;
    	this.location = location;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcb = new javax.swing.JComboBox();
        jb_ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt = new javax.swing.JTable();
        jp_button = new javax.swing.JPanel();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        
        for(int i = 1;i <LocationTypeArray.type.length;i++){
    		jcb.addItem(LocationTypeArray.type[i]);
    	}
        
        
        jLabel1.setFont(new java.awt.Font("幼圆", 1, 18));
        jLabel1.setText("自行车预约");

        jLabel2.setText("自行车类型：");

        jb_ok.setText("确定");
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jb_ok)
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ok)
                    .addComponent(jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("自行车预定（最大预定设备数量为1）", jPanel1);

      //表格的设置
        head = new Vector<String>();                         //设置表格头
        {head.add("自行车序列号");
        }
        data = new Vector<Vector>();                         //数据
        dtm = new DefaultTableModel(data,head);              //创建表格的模型
        jt = new javax.swing.JTable(dtm);                    //创建JTable的实例
        jt.setRowHeight(30);
        jScrollPane2.setViewportView(jt);
        jt.getColumnModel().getColumn(0).setHeaderValue("自行车序列号");

        javax.swing.GroupLayout jp_buttonLayout = new javax.swing.GroupLayout(jp_button);
        jp_button.setLayout(jp_buttonLayout);
        jp_buttonLayout.setHorizontalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        jp_buttonLayout.setVerticalGroup(
            jp_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jp_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jp_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(162, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
int count = 0;
int countNewOrederd = 0;
private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_okActionPerformed
	v_eqpId = new Vector<String>();
	String eqpType = (String) jcb.getSelectedItem();
	sql = "select eqp_id from view_lowerusers_ordered where eqp_type = '" +eqpType +"' AND eqp_location = '" + location +"'";
System.out.println(sql);
  
    try {
    	c = new SocketClient(sql,1);                           //实例化Client对象
    	c.send();                                        //将sql语句发送给服务器端处理
    	v_result = new Vector<String>();
    	v_result = c.getV_result();	                  //得到查询数据库后的结果
	 	} catch(Exception e){e.printStackTrace(); }                        //查询数据库

	 	Vector<String> v = null;
	    int num =0;
	    while(num<v_result.size()){
	    	v = new Vector<String>();
	    	for(int i = 0;i<1;i++){
			v.add(v_result.get(num));
			v_eqpId.add(v_result.get(count));
			num++;}
		  data.add(v);
		  newOrederd(count);
		  count++;                              //当前预定数量计数器加1
		  }
	    dtm.setDataVector(data, head);             		//更新table
	    jt.updateUI() ;                    //提示表格已更改
	    jt.repaint();                      //重绘表格
	
}




String str_now;
/************************************************************************
 *       为每个设备添加预定按钮                  	    
 * **********************************************************************/

    public void newOrederd(final int i ){
    	final JButton jb_renew = new JButton("预定");
    	jb_renew.setBounds(0,18+30*i,60,30);
    	jp_button.add(jb_renew);
    	
    	//“续借”按键  响应事件
    	jb_renew.addActionListener(new ActionListener(){                      
	        public void actionPerformed(ActionEvent event){
	        	
	        	if((countNewOrederd + orderedNum)>=MaxOrderedNum){
	        		JOptionPane.showMessageDialog(jp_button, "已经达到用户预定数量的上限，不能再预定设备！！","消息",
	        				JOptionPane.INFORMATION_MESSAGE);//弹出信息提示对话框
	            	return;
	        	}
	        	
	        	else{
	        	//........................获取当前时间点............................
	            Date now ;
	            DateFormat d = DateFormat.getDateInstance();
	            now = new Date();                                   
	            str_now = d.format(now); 
	          //....................................................................
	            sql = "insert into ordered(eqp_id,lower_user_id,eqp_location,ordered_time) " +
	            		"values ('" + v_eqpId.get(i)+"','" + userid +"','" + location +"',to_date('"+str_now+"','yyyy-mm-dd'))";
	        	
	            try {
	            	c = new SocketClient(sql);                           //实例化Client对象
	            	c.send();                                        //将sql语句发送给服务器端处理
	        	 	} catch(Exception e){e.printStackTrace(); }                        //查询数据库
	        	 	 if(Integer.parseInt(c.result) !=0){
	        	 		JOptionPane.showMessageDialog(jp_button, "预定设备"+v_eqpId.get(i)+"成功!!","消息",
		        				JOptionPane.INFORMATION_MESSAGE);//弹出信息提示对话框
		            	return;
	        	 	 }
	        	 	 else{
		        	 		JOptionPane.showMessageDialog(jp_button, "预定设备"+v_eqpId.get(i)+"失败!!","消息",
			        				JOptionPane.INFORMATION_MESSAGE);//弹出信息提示对话框
			            	return;
		        	 	 }
	        	}
	        	
	        	}});
	        
    	  }

private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded

	sql = "select count(*) from ordered where lower_user_id = '" + userid + "'";
	try {
		 c = new SocketClient(sql,1);                           //实例化Client对象
		 c.send();                                        //将sql语句发送给服务器端处理
		 v_result = new Vector<String>();
		 v_result = c.getV_result();	                  //得到查询数据库后的结果
		} catch(Exception e){e.printStackTrace(); }                        //查询数据库
	
	 orderedNum =Integer.parseInt(v_result.get(0)) ;	
	 if(orderedNum>=MaxOrderedNum){
		 jb_ok.setEnabled(false);
		 jLabel3.setText("用户当前预定数量为：" + v_result.get(0) + "，不可以再预定");
	 }
}//GEN-LAST:event_formAncestorAdded

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_ok;
    private javax.swing.JComboBox jcb;
    private javax.swing.JPanel jp_button;
    private javax.swing.JTable jt;
   

    public static void main(String args[]){
    	JFrame jf = new JFrame();
    	EquipmentOrdered seqp = new EquipmentOrdered("1221101","1406");
    	jf.add(seqp);
    	jf.setBounds(10,10,600,600);
    	jf.setVisible(true);
    }
}
