/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EquipmentOrdered.java
 *
 * Created on 2012-8-24, 20:24:20
 */
package superuserclient;

import java.text.DateFormat;
import java.util.Date;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import socketclient.ArrayObject;
import socketclient.SocketClient;





/**
 *
 * @author DELL
 */
public class EquipmentOrdered extends javax.swing.JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8793882778445539364L;
	private String userId;
    private String sql;
    private SocketClient c;
    long time;                         //设备剩余使用时间
    int count_borrowed;                //已预定设备计数器，记录用户已经借的设备
    
  //自己添加的变量	 
    Vector <String> head ;
    Vector<Vector> data;
    DefaultTableModel dtm;
    /** Creates new form EquipmentOrdered */
    public EquipmentOrdered(String userId ) {
    	this.userId = userId;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_ordered_show = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jp_order = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcb_eqpId = new javax.swing.JComboBox();
        jcb_orderedNum = new javax.swing.JComboBox();
        jcb_location = new javax.swing.JComboBox();
        jb_ok = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("圆幼", 1, 14));

      //表格的设置
        head = new Vector<String>();                         //设置表格头
        {head.add("自行车类型");
        head.add("预定数量");
        head.add("使用地点");
        head.add("剩余使用时间(天)");
        }
        data = new Vector<Vector>();                         //数据
        dtm = new DefaultTableModel(data,head);              //创建表格的模型
        jt_ordered_show = new javax.swing.JTable(dtm);                    //创建JTable的实例
        
        jt_ordered_show.setRowHeight(30);
        jScrollPane2.setViewportView(jt_ordered_show);

        jTabbedPane1.addTab("我预订的自行车", jScrollPane2);

        jScrollPane1.setViewportView(jTabbedPane1);

        jTabbedPane2.setFont(new java.awt.Font("圆幼", 1, 14)); // NOI18N

        jLabel1.setText("自行车类型");

        jLabel2.setText("预定数量");

        jLabel3.setText("使用地点");

        jcb_eqpId.setModel(new javax.swing.DefaultComboBoxModel(ArrayObject.type));

        jcb_orderedNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  1  ", "  2  ", "  3  " }));

        jcb_location.setModel(new javax.swing.DefaultComboBoxModel(ArrayObject.location));

        jb_ok.setText("确定");
        jb_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_orderLayout = new javax.swing.GroupLayout(jp_order);
        jp_order.setLayout(jp_orderLayout);
        jp_orderLayout.setHorizontalGroup(
            jp_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_orderLayout.createSequentialGroup()
                .addGroup(jp_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_orderLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jcb_eqpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_orderedNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jcb_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_orderLayout.createSequentialGroup()
                        .addContainerGap(454, Short.MAX_VALUE)
                        .addComponent(jb_ok)))
                .addGap(57, 57, 57))
        );
        jp_orderLayout.setVerticalGroup(
            jp_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_orderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jcb_orderedNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcb_eqpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jb_ok)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("预定自行车", jp_order);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jb_okActionPerformed(java.awt.event.ActionEvent evt) {
	System.out.println("--------------确定开始------------");
        String str_eqpType = ArrayObject.type[jcb_eqpId.getSelectedIndex()];          	 //设备类型
//        try{
//        str_eqpType =new String(str_eqpType.getBytes( "ISO-8859-1 "), "GB2312 ");}catch(Exception e){}
        System.out.println("自行车类型为：" +str_eqpType);
        int int_Num = jcb_orderedNum.getSelectedIndex()+1;          					//预借设备数量
       
        String str_location = ArrayObject.location[jcb_location.getSelectedIndex()]; 	//预借设备使用地点
        
        
       //........................获取点击处理按键的时间点............................
        Date now ;
        DateFormat d1 = DateFormat.getDateInstance();
        now = new Date(); 
        String str_now = d1.format(now);

        String sql = "insert into ordered_num(ordered_no,super_user_Id,eqp_type,num,eqp_location,ordered_time) values" +
        		"(ordered_num_seq.nextval,'"+userId+"','"+str_eqpType+"',"+int_Num+",'"+str_location+"',to_date('"+str_now +"','YYYY-MM-DD')) ";
      
        /*
         * 如果该用户预定数量已经达到了4
         * 则该用户不能预定
         * 否则可以预定
         * */
        System.out.println("------------"+count_borrowed);
        if(count_borrowed <4){
         try{
        	c = new SocketClient(sql);                  //创建客户端实例
        	c.send();                                    //发送给服务器端进行处理
        	}catch (Exception e){e.printStackTrace();}
           initTable();
            }
        else{
    	   JOptionPane.showMessageDialog(this, "预定次数超限，不能预定！！","消息",JOptionPane.INFORMATION_MESSAGE);//弹出信息提示对话框
	       return;}
        System.out.println("------------确定结束---------------");
   }

private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
    initTable();
}



Vector <String> v_result;
public void initTable(){
		count_borrowed=0;
		String str_now = null;                 //现在的时间
		data = new Vector<Vector>();
		
		 /*
		  * 获取点击处理按键的时间点
		  * */
        Date now ;
        DateFormat d1 = DateFormat.getDateInstance();
        now = new Date(); 
        str_now = d1.format(now);
System.out.println("现在的时间为："+str_now);		
        

        /*
         * 查询出该用户的已借设备
         * */
		sql = "select eqp_type,num,eqp_location,ordered_time " +
				"from ordered_num where super_user_Id = '" + userId +"'";		
	   try {
		 c = new SocketClient(sql,4);                           //实例化Client对象
		 c.send();                                        //将sql语句发送给服务器端处理
		 v_result = c.getV_result();	                  //得到查询数据库后的结果
		} catch(Exception e){e.printStackTrace(); }
		
		
		
		/*
		 * 将查询数据库后的结果显示在jTable里
		 * 因为服务器端处理后结果是以一位数组的形式传送的客户端的
		 * 所以：一、将一维数组转变成   n行4列   的二维数组
		 *               注意：第四列为剩余使用时间，则每一行的第四列都要计算时间差
		 *       二、更新jTable
		 * */
		Vector<String> v = null;
	    int num =0;
	    while(num<v_result.size()){
	    	v = new Vector<String>();
		  for(int j = 0;j < 4;j++){
			if(j!=3){v.add(v_result.get(num));}
			else{                                        //若为第四列，则计算时间差
				 String days = null;
				 try{
					 Date data_borrowed = d1.parse(v_result.get(num));
					 Date d_now = d1.parse(str_now);
					 long diff = d_now.getTime() - data_borrowed.getTime();
					 time = diff / (1000 * 60 * 60 * 24);
					 time = 60 - (time);
					 days = String.valueOf(time);        //剩余时间
					v.add(days);
                    }catch (Exception e){}
			 }    
			num++;
		  }	
		  data.add(v);
		  count_borrowed++;                              //已借设备计数器加1
		  }
	    dtm.setDataVector(data, head);             		//更新table
	    jt_ordered_show.updateUI() ;                    //提示表格已更改
	    jt_ordered_show.repaint();                      //重绘表格
		
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jcb_eqpId;
    private javax.swing.JComboBox jcb_orderedNum;
    private javax.swing.JComboBox jcb_location;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jb_ok;
    private javax.swing.JPanel jp_order;
    private javax.swing.JTable jt_ordered_show;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String args[]){
    	JFrame jf = new JFrame();
    	EquipmentOrdered seqp = new EquipmentOrdered("1221101");
    	jf.add(seqp);
    	jf.setBounds(10,10,600,600);
    	jf.setVisible(true);
    	
    }
}
