package superuserclient;

import java.io.UnsupportedEncodingException;
import java.sql.Statement;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import socketclient.SocketClient;


public class PwdModify extends javax.swing.JPanel {

	String sql;
	String userId;
	SocketClient c;
	Vector<String> v_result;
	
	 // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration
	
	
    public PwdModify(String userId) {
    	this.userId = userId;
    	initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("用户密码修改"));

        jLabel1.setText("原密码：");

        jLabel2.setText("新密码：");

        jLabel3.setText("确认密码：");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jButton1.setText("确认");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("重置");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
 
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>

 
//增加用户修改信息界面  原密码输入文本框响应事件
private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
	jTextField1.requestFocus();
}

//增加用户修改信息界面  新密码输入文本框响应事件
private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
	jTextField2.requestFocus();
}

//增加用户修改信息界面  "确认密码" 输入文本框响应事件
private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
	jTextField3.requestFocus();
}
String user_newpwd;
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt){
	
	
   //获取用户的 原密码
   String user_pwd = jTextField1.getText().trim();
   sql="select pwd from superusers where user_Id='" + userId+"'";
   
   
   try {
		 c = new SocketClient(sql,1);                           //实例化Client对象
		 c.send();                                        //将sql语句发送给服务器端处理
		 v_result = new Vector<String>();
		 v_result = c.getV_result();
		 System.out.println(v_result);
		} catch(Exception e){e.printStackTrace(); } 
		
   
   if(!user_pwd.equals(v_result.get(0))){
	   JOptionPane.showMessageDialog(this, "原密码输入错误，请重新输入！！！","错误",JOptionPane.INFORMATION_MESSAGE);
	  return;}
    else{
         user_newpwd= jTextField2.getText().trim();     //获取用户的“新密码”
         String patternStr = "[0-9]{1,10}";
          if(!user_newpwd.matches(patternStr)){
              JOptionPane.showMessageDialog(this, "请将用户密码限制在10个数字之内！！！","错误",JOptionPane.INFORMATION_MESSAGE);
             return;}
          else{
        	 String user_ensurepwd = jTextField3.getText().trim();//获取用户的“确认密码”
        	 if(!user_newpwd.equals(user_ensurepwd)){
        		 JOptionPane.showMessageDialog(this,"确认密码和原密码不相同，请重新输入！！！","错误",JOptionPane.INFORMATION_MESSAGE);
        		 return ;}
        	 else{
		   sql= "update superusers set pwd="+user_newpwd+" where user_Id='"+userId+"'";
		   System.out.println(sql);
		   try {
				 c = new SocketClient(sql);                           //实例化Client对象
				 c.send();                                        //将sql语句发送给服务器端处理
				 int i = Integer.parseInt(c.getResult());
				 	 if(i==1){
				 		 JOptionPane.showMessageDialog(this, "修改密码成功！！！","提示",JOptionPane.INFORMATION_MESSAGE);
				 	 }
				 	 else if(i!=1){
				 		 JOptionPane.showMessageDialog(this, "修改密码失败！！！","错误",JOptionPane.INFORMATION_MESSAGE); 
				 	 }
				} catch(Exception e){e.printStackTrace(); } 
        	 }
          }
    }
}

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
	jTextField1.setText("");
	jTextField2.setText("");
	jTextField3.setText("");
}

public static void main(String args[]){
	JFrame jf = new JFrame();
	jf.setBounds(20,30,300,320);
	PwdModify upm = new PwdModify("1221101");
	jf.add(upm);
	jf.setVisible(true);
	
} 

}



