package managerclient;

import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import socketclient.SocketClient;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbandonInformation.java
 *
 * Created on 2012-6-26, 8:55:04
 */

/**
 *
 * @author DELL
 */
public class AbandonInformation extends javax.swing.JPanel {

	   
	   String sql;
	   SocketClient c;
	   Vector<String> v_result;
	
	 // Variables declaration - do not modify
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JSeparator jSeparator1;
	    private javax.swing.JTable jTable1;
	    // End of variables declaration
	 
	  //自己添加的变量	 
	    Vector <String> head ;
	    Vector<Vector> data;
	    DefaultTableModel dtm;
	    
    /** Creates new form AbandonInformation */
    public AbandonInformation() {
    	initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("报废自行车信息");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        head = new Vector<String>();                         //设置表格头
        {head.add("自行车序列号");
        head.add("自行车类型类型");
        head.add("报废时间");
        }
        data = new Vector<Vector>();                         //数据
        dtm = new DefaultTableModel(data,head);              //创建表格的模型
        jTable1 = new javax.swing.JTable(dtm);                    //创建JTable的实例

        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(220, 220, 220))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>

private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {
	

	/*******************************************************************
	 * 在每次提交时，先清空jTable
	 * 清空jTable
	 * *****************************************************************/
        int sum = dtm.getRowCount();
        for (int j = 0; j < sum; j++)
        	dtm.removeRow(0);
        
   sql = "select abandon.eqp_Id,equipment.eqp_type,abandon.abandon_time from equipment,abandon where abandon.eqp_Id = equipment.eqp_Id";
 
   try {
		 c = new SocketClient(sql,3);                           //实例化Client对象
		 c.send();                                        //将sql语句发送给服务器端处理
		 v_result = new Vector<String>();
		 v_result = c.getV_result();	                  //得到查询数据库后的结果
		} catch(Exception e){e.printStackTrace(); }       //查询数据库
  
	/*
	 * 将查询结果放在二维数组data里
	 * */
	int num2 = 0;
	while(num2<v_result.size()){
		Vector<String> v = new Vector<String>();
		for(int i = 0;i<3;i++){
			v.add(v_result.get(num2));
			num2++;
		}
		data.add(v);         
		}
       	  dtm.setDataVector(data, head);             //更新table
          jTable1.updateUI() ;                            //提示表格已更改
          jTable1.repaint();                              //重绘表格
           
}

   public static void main(String[] args){
	   
	    JFrame jf = new JFrame();
		AbandonInformation abandoninf = new AbandonInformation();
		jf.add(abandoninf);
		jf.setBounds(10,10,600,600);
		jf.setVisible(true);
   }
}
