/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Route_epcId.java
 *
 * Created on 2013-6-19, 16:13:14
 */
/**
 *
 * @author DELL
 */
package routeShow;

import java.util.Vector;

import javax.swing.*;

import socketclient.SocketClient;

import common.Database;
public class RouteShow_V1 extends javax.swing.JPanel {

	SocketClient c;
	Vector<String> v_result;
  
    /** Creates new form Route_epcId */
    public RouteShow_V1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        panelName = new javax.swing.JLabel();
        jlb_name = new javax.swing.JLabel();
        jtf_eqpId = new javax.swing.JTextField();
        jbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jp_show = new javax.swing.JLayeredPane();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        panelName.setFont(new java.awt.Font("幼圆", 1, 36));
        panelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelName.setText("设备移动轨迹图");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(panelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(188, 188, 188))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jlb_name.setFont(new java.awt.Font("宋体", 0, 18));
        jlb_name.setText("自行车序列号：");
              
        jtf_eqpId.setBackground(new java.awt.Color(255, 255, 255));
        jtf_eqpId.setFont(new java.awt.Font("宋体", 0, 18));

        jbt.setBackground(new java.awt.Color(255, 204, 255));
        jbt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jbt.setText("查询");
        jbt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_show, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_show, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlb_name)
                .addGap(29, 29, 29)
                .addComponent(jtf_eqpId, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jbt))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_eqpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt)
                    .addComponent(jlb_name))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        
        
        JLabel jlb_waite = new JLabel();
        jlb_waite.setBounds(700, 100, 100, 20);
        jPanel1.add(jlb_waite);
        
    }// </editor-fold>//GEN-END:initComponents


private void jbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActionPerformed
// TODO add your handling code here:   
	int locate = 0;
	jp_show.removeAll();
   
	
    String time[]=new String[20];
    String action[]=new String[20];
    for(int i = 0;i<20;i++){
    action[0]="start-1";
    time[0]="start";}
    int cout =0;
	String eqpId=null;
    eqpId= jtf_eqpId.getText();//得到设备Id号
	System.out.println(eqpId);
	
	
	if(eqpId.equals("")){
		 JOptionPane.showMessageDialog(jp_show, "请输入设备号！！！","消息",JOptionPane.INFORMATION_MESSAGE);//弹出信息提示对话框
	}
	
else{
	
	
//	try {
//		 c = new SocketClient(sql,2);                           //实例化Client对象
//		 c.send();                                        //将sql语句发送给服务器端处理
//		 v_result = new Vector<String>();
//		 v_result = c.getV_result();	                  //得到查询数据库后的结果
//		} catch(Exception e){e.printStackTrace(); }  
//		System.out.println("-----------------------------2013-06-23:"+v_result);
//	for(int i = 0;i<v_result.size();i=i+2){
//		time[i] =v_result.get(i);
//		action[i] =v_result.get(i+1);
//		cout ++;
//	}
//	
//	System.out.println("--------------------------***************"+cout);
	String sql = "select movetime,action from route where eqp_id='"+eqpId+"' order by movetime";
	
	Database db = new Database();
	System.out.println(sql);
	try{
		db.searchDB(sql);
	while(db.rs.next()){
		System.out.println("-----------------"+db.rs.getString(1));
		time[cout]=db.rs.getString(1);
		action[cout]=db.rs.getString(2);
		cout++;
	}
	}catch(Exception e){}
	System.out.println("***********cout的值："+cout);
	System.out.println("***********action数组大小为：："+cout);
	if(cout!=0)
	{
		
	PanelLocation channel2= new PanelLocation("采购");
     channel2.setBounds(0, 50 ,80, 150);
     channel2.setOpaque(false);
     jp_show.add(channel2, new Integer(2));
     locate += 80;                //水平坐标值变为90
   
     for(int i=0;i<time.length;i++){
         
         if(i%2==1){
         PanelCondition condition= new PanelCondition(time[i],action[i]);//条件
         condition.setBounds(locate, 50 ,120, 150);
         condition.setOpaque(false);
         jp_show.add(condition, new Integer(2));
         locate +=120;
     
         PanelChannel channel = new PanelChannel(); //通道
         channel.setBounds(locate, 50 ,50, 150);
         channel.setOpaque(false);
         channel.setVisible(true);
         jp_show.add(channel, new Integer(2));
         locate +=50;
         }
         
         else if(i%2==0){
         String s[] = action[i].split("-");
         String strAddress =null;
         String strAction=null ;
         if(s.length>=2){
        	 strAddress= s[1];
        	 strAction = s[0]+s[1];
         	}

         PanelCondition condition= new PanelCondition(time[i],strAction);//条件
         condition.setBounds(locate, 50 ,120, 150);
         condition.setOpaque(false);
         jp_show.add(condition, new Integer(2));
         locate +=120;
         
         PanelLocation address= new PanelLocation(strAddress);//地点
        address.setBounds(locate, 50 ,80, 150);
        address.setOpaque(false);
        jp_show.add(address, new Integer(2));
        locate+=80;
        }
     }  
     }
	else{
		sql = "select eqp_Id from equipment where eqp_Id = '"+eqpId+"'";
		
//		try {
//			 c = new SocketClient(sql,1);                           //实例化Client对象
//			 c.send();                                        //将sql语句发送给服务器端处理
//			 v_result = new Vector<String>();
//			 v_result = c.getV_result();	                  //得到查询数据库后的结果
//			} catch(Exception e){}
//			if(v_result.size()!=0)
//	        	 JOptionPane.showMessageDialog(jp_show, "设备号在仓库未被使用过","消息",JOptionPane.INFORMATION_MESSAGE);//弹出信息提示对话框
//			else
//				JOptionPane.showMessageDialog(jp_show, "该设备号不存在！！","消息",JOptionPane.INFORMATION_MESSAGE);
//			
//			}
			
		
			
		db = new Database();
		db.searchDB(sql);
		try{
		if(db.rs.next())
        	 JOptionPane.showMessageDialog(jp_show, "自行车号在仓库未被使用过","消息",JOptionPane.INFORMATION_MESSAGE);//弹出信息提示对话框
		else
			JOptionPane.showMessageDialog(jp_show, "该序列号的自行车号不存在！！","消息",JOptionPane.INFORMATION_MESSAGE);
		
		}catch(Exception e){}
        }
		
	  
    
     
    }
    jp_show.repaint();//被集中
}//GEN-LAST:event_jbtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt;
    private javax.swing.JLabel jlb_name;
    private javax.swing.JLayeredPane jp_show;
    private javax.swing.JTextField jtf_eqpId;
    private javax.swing.JLabel panelName;
    // End of variables declaration//GEN-END:variables

public static void main(String args []){
   String time[]={"2013-05-15 18:20","2013-05-17 17:50","2013-07-10 16:18","2013-07-10 18:18"};
   String action[]={"出库","在校园","离开校园","进入/仓库"};
    
    	JFrame jf = new JFrame();
    	RouteShow_V1 route = new RouteShow_V1();
    	jf.add(route);
    	jf.setBounds(10,10,800,800);
    	jf.setVisible(true);
}

}
